services:
  - type: web
    name: tecnopos
    runtime: node
    plan: free
    buildCommand: npm run install:all && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SEED_ON_BOOT
        value: true
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_ORIGIN
        value: https://tecnopos.onrender.com
